### ISSUE TITLE
authController.js: Add short meaningful comments between and inside APIs explaining their working

### ISSUE THREAD

**Issue by alanansari** [Tweeter-Org/tweeter-backend#2]

**Comment by ShrutiKolla** [comment]
@alanansari Can I work on this? Please assign me.

**Comment by ShrutiKolla** [comment]
@alanansari I have to add comments only in authContoller.js ?

**Comment by alanansari** [comment]
@ShrutiKolla if u can add it to all controllers else just this would suffice

**Comment by ShrutiKolla** [comment]
@alanansari I created a PR. Can you review it? I will make changed if you mention some.
