### ISSUE TITLE
Postman api docs is broken

### ISSUE THREAD

**Issue by sugan0tech** [Tweeter-Org/tweeter-backend#4]
Issue: 
tried to check the API documentation and found this.
![Screenshot 2023-10-07 at 9 39 08 AM](https://github.com/Tweeter-Org/tweeter-backend/assets/71312159/fa94d6b8-53c5-404f-9abc-47a8a9f21855)

**Comment by alanansari** [comment]
I'll be working on this myself, will update you guys soon :)
