### ISSUE TITLE
Rename all model and controller files and add an index.js inside them to export

### ISSUE THREAD

**Issue by alanansari** [Tweeter-Org/tweeter-backend#5]
**Current Example**
<img width="194" alt="image" src="https://github.com/Tweeter-Org/tweeter-backend/assets/22475370/c489b152-fea5-4b23-b457-00efe259812b">
**Required Example**
<img width="140" alt="image" src="https://github.com/Tweeter-Org/tweeter-backend/assets/22475370/8bd05ce4-650f-4024-ac9b-eebc544f7bb6">
_index.js_
<img width="338" alt="image" src="https://github.com/Tweeter-Org/tweeter-backend/assets/22475370/d2424bc5-51c4-4614-a9c3-89938951894c">
<br>
With this change all the imports as well, making it single import separated through commas.
_Example:_
<img width="330" alt="image" src="https://github.com/Tweeter-Org/tweeter-backend/assets/22475370/ed3fc88b-328f-4daa-9efb-9808965a8f85">

**Comment by mohammadanang** [comment]
Hello @alanansari, can I take this issue?
