### ISSUE TITLE
Create a Beautiful README File

### ISSUE THREAD

**Issue by alanansari** [Tweeter-Org/tweeter-backend#6]
Take reference from the frontend repository's readme and create something like that for this too.
[Frontend Readme](https://github.com/Tweeter-Org/tweeter-frontend/#readme)

**Comment by Harshavii** [comment]
Hi, I can work on this, please assign me.

**Comment by alanansari** [comment]
@Harshavii any updates?

**Comment by Harshavii** [comment]
@alanansari should I add more content like guidelines, steps to contribute, etc as in [frontend repo](https://github.com/Tweeter-Org/tweeter-frontend/#readme) or just reformat the original content?

**Comment by alanansari** [comment]
@Harshavii Yes please. Add all that too

**Comment by Harshavii** [comment]
okay. checkout pr #15.
